flowchart LR
subgraph input
i0(player)
i1(m.wood)
i2(m.rice)
i3(m.land)
i4(p0.rice)
i5(p0.wood)
i6(p0.land)
i7(p0.farm)
i8(p0.forest)
i9(p0.gold)
i10(p0.debt)
end
subgraph net
n11(n11 : const : 0.349)
end
n11 -.-> decision