version: '3.5'
services:
    database:
        container_name: database_container
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: gaimemaster
            POSTGRES_DB: gaime
        ports:
            - '5432:5432'
        volumes:
            - database-volume:/var/lib/database
    snake-server:
        container_name: snake_server_container
        build: ./snake/server
        volumes:
            - './snake/server:/usr/src/snake/server'
        ports:
            - '8080:8080'
        command: snake_server
    server:
        container_name: server_container
        build: ./server
        volumes:
            - './server:/usr/src/server'
        ports:
            - '8000:8000'
        command: server
        links:
            - database
#    server_node:
#        container_name: server_node_container
#        build: ./server_node
#        volumes:
#            - './server_node:/usr/src/server_node'
#        ports:
#            - '8000:8000'
#        command: npm start
#        environment:
#            PGHOST: database
#            PGUSER: gaimemaster
#            PGDATABASE: gaime
#            PGPASSWORD: password
#            PGPORT: 5432
#        links:
#            - database
    client:
        container_name: client_container
        build: ./client
        volumes:
            - './client:/usr/src/client'
        ports:
            - '4200:4200'
        command: ng serve --host 0.0.0.0 --port 4200
volumes:
    database-volume:
