version: '3.5'
services:
    database:
        container_name: database_container
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: gaimemaster
            POSTGRES_DB: gaime
        ports:
            - '5432:5432'
        volumes:
            - database-volume:/var/lib/database
    game-luck-server:
        container_name: game_luck_server_container
        build: ./games/luck/server
        volumes:
            - './games/luck/server:/usr/src/games/luck/server'
        ports:
            - '${GAME_LUCK_PORT}:${GAME_LUCK_PORT}'
        command: game_luck_server
        links:
            - server
        environment:
            - RUST_BACKTRACE=full
            - API_ROOT_URL=${API_ROOT_URL}
            - GAME_LUCK_URL=${GAME_LUCK_URL}
    snake-server:
        container_name: snake_server_container
        build: ./snake/server
        volumes:
            - './snake/server:/usr/src/snake/server'
        ports:
            - '${GAME_SNAKE_PORT}:${GAME_SNAKE_PORT}'
        command: snake_server
        links:
            - server
        environment:
            - RUST_BACKTRACE=full
    server:
        container_name: server_container
        build: ./server
        volumes:
            - './server:/usr/src/server'
        ports:
            - '8000:8000'
        command: server
        links:
            - database
        environment:
            - RUST_BACKTRACE=full
    client:
        container_name: client_container
        build: ./client
        volumes:
            - './client:/usr/src/client'
        ports:
            - '4200:4200'
        command: ng serve --host 0.0.0.0 --port 4200
volumes:
    database-volume:
