flowchart LR
subgraph input
i0(turn)
i1(player)
i2(m.wood)
i3(m.rice)
i4(m.land)
i5(p0.rice)
i6(p0.wood)
i7(p0.land)
i8(p0.farm)
i9(p0.forest)
i10(p0.gold)
i11(p0.debt)
i12(p1.rice)
i13(p1.wood)
i14(p1.land)
i15(p1.farm)
i16(p1.forest)
i17(p1.gold)
i18(p1.debt)
i19(p2.rice)
i20(p2.wood)
i21(p2.land)
i22(p2.farm)
i23(p2.forest)
i24(p2.gold)
i25(p2.debt)
end
subgraph net
i0 -.-> n0 
n0(n0 : in)
i1 -.-> n1 
n1(n1 : in)
i2 -.-> n2 
n2(n2 : in)
i3 -.-> n3 
n3(n3 : in)
i4 -.-> n4 
n4(n4 : in)
i5 -.-> n5 
n5(n5 : in)
i6 -.-> n6 
n6(n6 : in)
i7 -.-> n7 
n7(n7 : in)
i8 -.-> n8 
n8(n8 : in)
i9 -.-> n9 
n9(n9 : in)
i10 -.-> n10 
n10(n10 : in)
i11 -.-> n11 
n11(n11 : in)
i12 -.-> n12 
n12(n12 : in)
i13 -.-> n13 
n13(n13 : in)
i14 -.-> n14 
n14(n14 : in)
i15 -.-> n15 
n15(n15 : in)
i16 -.-> n16 
n16(n16 : in)
i17 -.-> n17 
n17(n17 : in)
i18 -.-> n18 
n18(n18 : in)
i19 -.-> n19 
n19(n19 : in)
i20 -.-> n20 
n20(n20 : in)
i21 -.-> n21 
n21(n21 : in)
i22 -.-> n22 
n22(n22 : in)
i23 -.-> n23 
n23(n23 : in)
i24 -.-> n24 
n24(n24 : in)
i25 -.-> n25 
n25(n25 : in)
n1 -.-> n26 
n4 -.-> n26 
n26(n26 : out)
n14 -.-> n27 
n23 -.-> n27 
n0 -.-> n27 
n23 -.-> n27 
n8 -.-> n27 
n27(n27 : out)
n5 -.-> n28 
n0 -.-> n28 
n28(n28 : out)
n25 -.-> n29 
n18 -.-> n29 
n2 -.-> n29 
n31 -.-> n29 
n29(n29 : weight : 0.373)
n0 -.-> n30 
n16 -.-> n30 
n8 -.-> n30 
n25 -.-> n30 
n30(n30 : weight : 0.090)
n31(n31 : const : 0.263)
n32(n32 : decision)
n33(n33 : hardtanh)
n34(n34 : weight : 0.553)
n35(n35 : decision)
n36(n36 : decision)
end
n26 -.-> decision
n27 -.-> decision
n28 -.-> decision