[package]
name = "snake_server"
version = "0.1.0"
authors = ["loicbourgois <loic@bourgois.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
serde_json = "1"
serde = "1"
serde_derive = "1"
rand = "0.7"
